name: Terraform CD

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura credenciais AWS (com sessão, se for AWS Academy)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Garante que o bucket do backend existe
      - name: Ensure backend bucket exists
        run: ./create_backend_bucket.sh

      # Recupera account ID da AWS
      - name: Get AWS Account ID
        id: aws_account
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "account_id=$ACCOUNT_ID" >> $GITHUB_ENV

      # Inicializa o backend
      - name: Terraform Init
        run: terraform init -reconfigure

      # Valida os arquivos
      - name: Terraform Validate
        run: terraform validate

      # Aplica as mudanças
      - name: Terraform Apply
        run: terraform apply -var="account=${{ env.account_id }}" -auto-approve
